language: python
sudo: required
matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
      python: 2.7
    - os: linux
      dist: bionic
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
      python: 3.5
    - os: linux
      dist: bionic
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
      python: 3.6
    - os: linux
      dist: bionic
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
      python: 3.7
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
# command to install dependencies
install: make setup
# command to run tests
script:
    - make test
